# Copyright 2026 cklxx
#
# Licensed under the MIT License.

from fastdistill.steps.tasks.evol_instruct.utils import (
    GENERATION_MUTATION_TEMPLATES as GENERATION_MUTATION_TEMPLATES_EVOL_INSTRUCT,
)
from fastdistill.steps.tasks.evol_instruct.utils import (
    MUTATION_TEMPLATES as MUTATION_TEMPLATES_EVOL_INSTRUCT,
)

MUTATION_TEMPLATES = {
    "CONSTRAINTS": MUTATION_TEMPLATES_EVOL_INSTRUCT["CONSTRAINTS"],
    "DEEPENING": MUTATION_TEMPLATES_EVOL_INSTRUCT["DEEPENING"],
    "CONCRETIZING": MUTATION_TEMPLATES_EVOL_INSTRUCT["CONCRETIZING"],
    "INCREASED_REASONING_STEPS": MUTATION_TEMPLATES_EVOL_INSTRUCT[
        "INCREASED_REASONING_STEPS"
    ],
}

GENERATION_MUTATION_TEMPLATES = {
    "FRESH_START": GENERATION_MUTATION_TEMPLATES_EVOL_INSTRUCT["FRESH_START"],
    "CONSTRAINTS": GENERATION_MUTATION_TEMPLATES_EVOL_INSTRUCT["CONSTRAINTS"],
    "DEEPENING": GENERATION_MUTATION_TEMPLATES_EVOL_INSTRUCT["DEEPENING"],
    "CONCRETIZING": GENERATION_MUTATION_TEMPLATES_EVOL_INSTRUCT["CONCRETIZING"],
    "INCREASED_REASONING_STEPS": GENERATION_MUTATION_TEMPLATES_EVOL_INSTRUCT[
        "INCREASED_REASONING_STEPS"
    ],
}
